### ISSUE TITLE
Cannot find calculate_AG graphs

### ISSUE THREAD

**Issue by Liverworks** [shelkmike/Mabs#2]
Hello and thank you for your tool!

I ran Mabs-hifiasm, and it worked very well. Especially, it improves polyploid assemblies compared to hifiasm. 

So, could you please explain the `--ploidy` option a bit? We have both allo- and autopolyploid species, and we need to know how this option may impact the assemblies.

The second thing, I could not find `gene_coverage_distribution.svg` and `.png` after running `calculate_AG.py`. Files `AG.txt`, `list_of_coverages.txt` and `logs.txt` are fine.

**Comment by shelkmike** [comment]
Hi

The option --ploidy in Mabs-hifiasm corresponds to the option --n-hap in Hifiasm. If you run Mabs-hifiasm with "--ploidy 4", then Mabs-hifiasm will run Hifiasm with "--n-hap 4". Unfortunately, how the option --n-hap works is not described anywhere in the articles and in the manual of Hifiasm. So, I cannot explain the algorithm behind it.
According to the help of Hifiasm,
`
--n-hap <INT=2>     
    Assumption of haplotype number. If it is set to >2, the quality of primary assembly for polyploid genomes might be improved.
`

See also https://hifiasm.readthedocs.io/en/latest/faq.html#are-polyploid-genomes-supported

This is actually a very good question. I didn't work with polyploids, so I wasn't interested in it much. Now I have asked the author of Hifiasm, see https://github.com/chhylp123/hifiasm/issues/433

Regarding the diagrams. Could you please attach the stdout and stderr of calculate_AG, so I can check it?

**Comment by Liverworks** [comment]
Thank you very much for clarifying the ploidy option! 

About the calculate_AG function. I have this error message:

> Traceback (most recent call last):
  File "/software/Mabs-2.14/Additional/plot_gene_coverage_distribution.py", line 77, in <module>
    o_plot = plotnine.ggplot(o_data_frame) + plotnine.aes(x = "", y = "Sequencing coverage") + plotnine.geom_sina(color = "#4472C4", scale = "area", size = n_point_size) + plotnine.scales.scale_x_discrete(limits = ["Genes from\nsingle-copy\northogroups", "Genes from\nmulticopy\northogroups"]) + plotnine.scales.scale_y_continuous(expand = (0, 0), limits = (0, n_maximum_coverage_to_draw)) + plotnine.theme_light() + plotnine.theme(text = plotnine.element_text(linespacing = 1.1))
AttributeError: module 'plotnine' has no attribute 'geom_sina'

**Comment by shelkmike** [comment]
Thank you. It seems that you have an old version of Plotnine which doesn't have the function "geom_sina". Please, run the following command to upgrade Plotnine:
`python3 -m pip install --upgrade --user Plotnine`

I'll fix this problem in the next version of Mabs, so users will not need to upgrade Plotnine manually.
Thank you for reporting this issue!

**Comment by shelkmike** [comment]
@Liverworks 
I wonder, did you try Mabs-flye for this assembly? There is a chance that it would be better for a polyploid than Mabs-hifiasm.

**Comment by Liverworks** [comment]
Hi @shelkmike !

Thank you for the advice. I've tried Mabs-flye, but in my case Mabs-hifiasm results are far much better.
