### ISSUE TITLE
Invalid character (.) in sequence at line 2636 of reference_busco_proteins.fasta

### ISSUE THREAD

**Issue by spoonbender76** [shelkmike/Mabs#3]
Hi! Thank you for the tool!

I installed Mabs and finished `mabs-hifiasm.py --run_test` without problem. 

When test on my own case using command
`nohup /usr/bin/time -v /home/snow/ssd/programs/Mabs-2.19/mabs-hifiasm.py \`
`--pacbio_hifi_reads ../Nm_merge.fastq \`
`--download_busco_dataset hemiptera_odb10.2020-08-05.tar.gz \`
`--number_of_busco_orthogroups all \`
`--threads 128 > mabs.log 2>&1 &` 

There's an error showing in [mabs.log](https://github.com/shelkmike/Mabs/files/11449949/mabs.log).
> #CPU threads: 128
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Database input file: ./Mabs_results/reference_busco_proteins.fasta
Opening the database file...  [0s]
Loading sequences...  [0.005s]
Error: Error reading input stream at line 2636: Invalid character (.) in sequence
Traceback (most recent call last):
&nbsp;&nbsp;File "/home/snow/ssd/programs/Mabs-2.19/Additional/get_single_end_reads_from_DIAMOND_results.py", line 25, in <module>`
&nbsp;&nbsp;&nbsp;&nbsp;f_DIAMOND_results = open(sys.argv[2], "r")
FileNotFoundError: [Errno 2] No such file or directory:
'./Mabs_results/diamond_results_for_alignment_of_pacbio_hifi_reads_to_busco_proteins.txt'

and Mabs ended up like: 
>Writing ./Mabs_results/Assembly_for_-s_0.382/assembly.bp.p_ctg.gfa to disk... 
Modified_hifiasm finishes because the user has provided the option "--only-primary"There was an error in the command line of calculate_AG:
The file with PacBio HiFi reads ./Mabs_results/pacbio_hifi_reads_that_have_matches_to_busco_proteins.fastq does not exist.
>
>calculate_AG has stopped. Please, fix this error and restart calculate_AG.

line 2635 and 2636 of [reference_busco_proteins.fasta](https://github.com/spoonbender76/issue_reports/blob/main/reference_busco_proteins.fasta):
>&gt;17976at7524
MIIPIRCFTCGKVIANKWESYLGLLQAEYTEGDALDALGLKRYCCRRMLLGHVDLIEKLLNYAPLEK.

There's a '.' at the end of line 2636 causing the error.
Further, I found 689 '.' in the original refseq_db.faa file extracted from hemiptera_odb10.2020-08-05.tar.gz
I don't know why '.' exists in their fasta file. Does it has any special purposes? Or can I just remove all '.'  and rerun? 

Files from /Mabs_results:
[mabs_logs.txt](https://github.com/shelkmike/Mabs/files/11449945/mabs_logs.txt)
[diamond__pacbio_hifi_reads_to_busco_proteins__stdout.txt](https://github.com/shelkmike/Mabs/files/11449946/diamond__pacbio_hifi_reads_to_busco_proteins__stdout.txt)
[diamond__pacbio_hifi_reads_to_busco_proteins__stderr.txt](https://github.com/shelkmike/Mabs/files/11449947/diamond__pacbio_hifi_reads_to_busco_proteins__stderr.txt)

Some other thoughts:

Mabs continued to run modified_hifiasm for hours when diamond error popped up. Maybe it should have detected earlier if there is a `pacbio_hifi_reads_that_have_matches_to_busco_proteins.fastq` file before running modified_hifiasm.

Btw when I want to check if mabs-flye.py is ok by using `mabs-flye.py --run_test` right after `mabs-hifiasm --run_test` and it will show:
>snow@snow:~$ /home/snow/ssd/programs/Mabs-2.19/mabs-flye.py --run_test
Mabs-flye has stopped because the output folder already exists and is not empty.

I have to delete the existed mabs-hifiasm test folder then run mabs-flye test.
It can be fixed by adding a suffix to test folder name like `mabs_test_flye` to avoid this unnecessary step.

P.S. I'm really looking forward to the results of this tool because I'm having trouble with default hifiasm/flye assembly for my HiFi reads and getting like 86.8%/94.7% D score in busco without purge_dups, considering 

> purge_dups was detrimental (it decreased AG) for all assemblies from HiFi reads

**Comment by shelkmike** [comment]
Thank you for this error report. This "." is a mistake in a BUSCO dataset. I'll consult with the authors of BUSCO on how it got there. Now I have removed this character from the dataset. Please, rerun the analysis.
I will fix Mabs so it will stop after similar errors. This will be implemented in the next release.
I'll think about changing the default naming of the output folders.
