### ISSUE TITLE
--only-primary

### ISSUE THREAD

**Issue by gunjanpandey** [shelkmike/Mabs#4]
Could you please tell how to disable `--only-primary ` flag?

Following command is giving the error
`mabs-hifiasm.py --threads 64 --pacbio_hifi_reads .hifi.fq --local_busco_dataset diptera_odb10/ ` 

tail of the error log file
`
[M::purge_dups] homozygous read coverage threshold: 46
[M::purge_dups] purge duplication coverage threshold: 58
[M::mc_solve:: # edges: 8902]
[M::mc_solve_core_adv::1.395] ==> Partition
[M::adjust_utg_by_primary] primary contig coverage range: [39, infinity]
Writing ./Mabs_results/Assembly_for_point_1/assembly.bp.p_ctg.gfa to disk...
Modified_hifiasm finishes because the user has provided the option "--only-primary"  File "/apps/mabs/2.24/bin/calculate_AG.py", line 44
    if shutil.which("bedtools") is None:
                                        ^
IndentationError: unindent does not match any outer indentation level
`

Following is the "Mabs_results/ " folder structure...  
`analysis_of_BUSCO_HMMs.txt
reference_busco_proteins.fasta.dmnd
reference_busco_proteins.fasta
diamond__pacbio_hifi_reads_to_busco_proteins__stdout.txt
BUSCO_dataset_to_use/
diamond_results_for_alignment_of_pacbio_hifi_reads_to_busco_proteins.txt
diamond__pacbio_hifi_reads_to_busco_proteins__stderr.txt
pacbio_hifi_reads_that_have_matches_to_busco_proteins.fastq
mabs_log.txt
Assembly_for_point_1/
`

Following is the  "Mabs_results/Assembly_for_point_1/" folder structure
`assembly.ec.bin
assembly.ovlp.source.bin
assembly.ovlp.reverse.bin
assembly.bp.r_utg.gfa
assembly.bp.r_utg.noseq.gfa
assembly.bp.r_utg.lowQ.bed
assembly.bp.p_utg.gfa
assembly.bp.p_utg.noseq.gfa
assembly.bp.p_utg.lowQ.bed
assembly.bp.p_ctg.gfa
assembly.fasta
`

**Comment by shelkmike** [comment]
Hi. First of all, thank you for the error report.

You can disable --only-primary if you remove all four instances of "--only-primary " (with space in the end) in the source code of mabs-hifiasm.py
Why would you do this? The final assembly (after Mabs has determined the optimal value of "-s") is performed without this parameter, thus in the final assembly you will have phased contigs too.

Also, the problem that you encounter ("IndentationError: unindent does not match any outer indentation level") is not related to the use of --only-primary. It probably happened because I use tabs for indentation and you modified the code of calculate_AG.py using spaces instead of tabs. Python doesn't like when both spaces and tabs are used for indentation in one file. Am I correct that you modified the code of calculate_AG.py?

**Comment by gunjanpandey** [comment]
Thanks for your prompt reply, Mike. 

Since I was not getting any other folder besides "Assembly_for_point_1/", I thought --primary-only could be the reason. 
Our HPC folks installed the software so I can't say if they have modified the code - but most likely they did. 

Could you please tell what could be done to make the program go all the way and give the The FInal Assembly? 
Could the  IndentationError: error above be the reason?

Happy to provide you full log. Please let me know.

**Comment by shelkmike** [comment]
Just tell the person who installed Mabs and modified the code of calculate_AG.py to use tabs instead of spaces for indentation. This will fix the problem.

**Comment by shelkmike** [comment]
@gunjanpandey 
Was the problem solved?

**Comment by gunjanpandey** [comment]
Yes, it is fixed. Thank you.

**Comment by OH-AU** [comment]
@shelkmike reasoning for making changes in case you want to modify your scripts:

All references to applications in "Additional" e.g.:
> 	if not os.path.isfile(s_path_to_the_folder_where_Mabs_lies + "/Additional/Bedtools/bedtools"):
> 		l_unavailable_files_and_folders.append("The file " + s_path_to_the_folder_where_Mabs_lies + "/Additional/Bedtools/bedtools has not been found")

were replaced with:

< 	if shutil.which("bedtools") is None:
< 		l_unavailable_files_and_folders.append("\"bedtools\" is not in $PATH")

as we have our own optimised versions of all the tools in your workflow. Only had to installed your custom version of hifiasm .
Calls to the applications have also been simplifed e.g

from (mabs-hifiasm.py):
os.system(s_path_to_the_folder_where_Mabs_lies + "/Additional/DIAMOND/diamond makedb --in " + s_path_to_the_output_folder + "/reference_busco_proteins.fasta -d " + s_path_to_the_output_folder + "/reference_busco_proteins.fasta")

to:
os.system("diamond makedb --in " + s_path_to_the_output_folder + "/reference_busco_proteins.fasta -d " + s_path_to_the_output_folder + "/reference_busco_proteins.fasta")

Perhaps an alternative would be to symlink all the binaries into a directory and add that to the path?

**Comment by shelkmike** [comment]
@OH-AU 
Thank you for the information. Actually, Modified_hifiasm is the most time consuming program in Mabs-hifiasm, so optimization of other programs will probably not accelerate Mabs-hifiasm significantly.
