### ISSUE TITLE
Is it possible to run mabs-flye with checkpointing?

### ISSUE THREAD

**Issue by mergi-2674** [shelkmike/Mabs#5]
Hi shelkmike

I was running MABS-Flye on a cluster to assemble a plant genome. However, after MABS-Flye successfully executed the parameter optimization step, it began the final round but stopped because the cluster has a fixed time limit that cannot be extended. Is MABS-Flye, like some software designed to run for an extended period, able to save its progress and restart from checkpoints?

Best
Mergi!

**Comment by shelkmike** [comment]
Hi. Unfortunately, Mabs currently cannot resume its work from an intermediate point when it's interrupted. I will probably add this functionality in the future. If Mabs-flye stopped working in the last stage, you can make the assembly yourself using values of parameters that Mabs considered optimal. Look into log.txt. In that file you'll see a sentence like "The optimal combination of Flye parameters as determined by Mabs-flye is: assemble_ovlp_divergence = 0.223795, repeat_graph_ovlp_divergence = 0.04, assemble_divergence_relative = 0". Just run Flye providing these values of parameters. Which means, a command should look like this:
`flye --nano-raw PATH_TO_YOUR_READS --threads SOME_NUMBER_OF_THREADS --no-alt-contigs --extra-params assemble_ovlp_divergence=0.223795,repeat_graph_ovlp_divergence=0.04,assemble_divergence_relative=0`
