### ISSUE TITLE
Unable to complie programs 

### ISSUE THREAD

**Issue by GiangLeN** [shelkmike/Mabs#6]
Hi,

I am working on a server and do not have sudo power. All the programs and packages have to be installed via conda.
When I try to run `install.sh` I get the following error:

```
CommandLines.cpp:2:10: fatal error: zlib.h: No such file or directory
    2 | #include <zlib.h>
```

Zlib was installed but could be be detected.

Do you have a compiled version that I can try?

Thank you so much for your time.

Best regards,
Giang

**Comment by shelkmike** [comment]
Hi. Mabs requires not just zlib, but zlib-dev. If you use Conda, this command may solve the problem: `conda install anaconda::zlib-devel-amzn2-aarch64`

Also, tomorrow I will upload to GitHub a new version of Mabs which can be run from a Singularity container. If you have Singularity on your server, you'll be able to run Mabs without installation.

**Comment by shelkmike** [comment]
Hi. Mabs requires not just zlib, but zlib-dev. I doubt that it can be installed via Conda. Zlib-dev is a basic Linux package. It's probably better to ask the system administrator to install it using `sudo apt-get install zlib1g-dev` or `sudo yum install zlib-devel`, depending on the version of Linux.

Also, tomorrow I will upload to GitHub a new version of Mabs which can be run from a Singularity container. If you have Singularity on your server, you'll be able to run Mabs without installation.

**Comment by GiangLeN** [comment]
Hi,

It would be great to try Mabs from singularity. Please let me now when you upload the new version on Github.

Many thanks,
Giang

**Comment by shelkmike** [comment]
You can download a Singularity container from https://mikeshelk.site/Diff/Mabs_distribution/Singularity_containers/ . To see information about how to use it, run `singularity run-help mabs.sif`
