### ISSUE TITLE
Hi-C reads from multiple lanes

### ISSUE THREAD

**Issue by Siadjeu** [shelkmike/Mabs#7]
Hey Shelmike,

I was wondering how to integrate Hi-C reads from multiple lanes with Mabs. For instance, I have reads like these: A_L1_R1.fq.gz, A_L1_R2.fq.gz, A_L2_R1.fq.gz, and A_L2_R2.fq.gz. Thank you in advance!

Best

**Comment by shelkmike** [comment]
Hi. You can concatenate reads from different lanes into one file:
```
cat A_L1_R1.fq.gz A_L2_R1.fq.gz >A_R1.fq.gz
cat A_L1_R2.fq.gz A_L2_R2.fq.gz >A_R2.fq.gz
```
After that, you can do adapter trimming (for example, using Fastp https://github.com/OpenGene/fastp) and give reads to Mabs-hifiasm.
But keep in mind that Hifiasm (and, consequently, Mabs-hifiasm) uses Hi-C reads for haplotype phasing and not for scaffolding. If you want to do Hi-C scaffolding, you can give contigs made by Mabs-hifiasm to YaHS (https://github.com/c-zhou/yahs).

**Comment by Siadjeu** [comment]
Hey, Thank you for your response and helpful suggestions! I was advised that when working with Hi-C reads, it is not recommended to concatenate them with the "cat" command. This is because it may cause the order and orientation of reads to be lost, which is crucial for phasing and scaffolding. What is your opinion on this matter?

**Comment by shelkmike** [comment]
You shouldn't merge files with reads of the first end ("R1") and of the second end ("R2") into one file. However, merging files that belong to different lanes is completely normal.

**Comment by Siadjeu** [comment]
Okay thank you!
