### ISSUE TITLE
Unable to generate final assembly file

### ISSUE THREAD

**Issue by asifratul** [shelkmike/Mabs#9]
Hi, 

I am running following code -

mabs-hifiasm.py \
--pacbio_hifi_reads output_filtered.fastq \
--local_busco_dataset laurasiatheria_odb10.2024-01-08.tar.gz \
--threads 64

but it is getting following error. 

"ERROR-purge
[M::adjust_utg_by_primary] primary contig coverage range: [45, infinity]
Writing ./Mabs_results/Assembly_for_point_1/assembly.bp.p_ctg.gfa to disk... 
Modified_hifiasm finishes because the user has provided the option "--only-primary"There were errors with unavailable files:
1) The file proovframe-map has not been found
2) The file proovframe-fix has not been found

calculate_AG has stopped. Please, fix these errors and restart calculate_AG."

giving following files - 
![image](https://github.com/shelkmike/Mabs/assets/40979705/53ce7c40-9004-45f9-810c-7a94a9128b06)

Can you please let me know, if there is any fix?

ASIF

**Comment by shelkmike** [comment]
Hi. In the folder with mabs-hifiasm.py there should be a subfolder named "Additional", which, in turn, should have a subfolder "Proovframe". Could you please check that it exists?

**Comment by asifratul** [comment]
I am afraid it is not there!

![image](https://github.com/shelkmike/Mabs/assets/40979705/99ea930a-db17-403c-bf26-194582d63308)

**Comment by shelkmike** [comment]
This is quite strange. Maybe you accidentally deleted it. Please, install Mabs as described in Readme. This should help.

**Comment by shelkmike** [comment]
@asifratul 
Were you able to solve the problem?

**Comment by asifratul** [comment]
Thanks for following up. I have re-installed the package with “additional” folder. Test run completed with success. Now running on main data. Hope it should be fine also! Thanks for your prompt reply and support.
